### ISSUE TITLE
Make sure backlog is DEEP (8)

### ISSUE THREAD

**Issue by otsohelos** [akirataguchi115/lukuvinkkikirjasto#17]
(detailed appropriately, estimated, emergent ja prioritized)

**Comment by lambdakilo** [comment]
- Backlog User stories and tasks have been detailed to a point where the customer knows what they're getting and the developer knows what to do next with the task.
- Backlog tasks contain the estimated time and the actual time
- New User stories and tasks have emerged to the backlog during and in between sprints
- User stories have been prioritized during(f.ex. sudden large scale failing of tests) and between sprints
