### ISSUE TITLE
Open sensitive information 

### ISSUE THREAD

**Issue by Nurou** [akirataguchi115/lukuvinkkikirjasto#65]
The application's properties (e.g. db credentials) should be passed as environment variables. They are currently exposed.

**Comment by lacolegiala** [comment]
Where exactly are the application's properties passed?

**Comment by Nurou** [comment]
https://github.com/akirataguchi115/lukuvinkkikirjasto/blob/e6bbdb3b4b82dd9d3702c41ae84d772f2e3c9bd3/src/main/resources/application.properties#L1-L11
